plugins:
  category_custom_field_enabled:
    default: true
    client: true
  post_view_enabled:
    default: 'list'
    client: true
    type: enum
    choices:
      - grid
      - list
  tabs_view_enabled:
    default: true
    client: true
  user_can_create_post_enabled:
    default: true
    client: true
  show_main_post_enabled:
    default: false
    client: true